name: Record
options:
  bundleIdPrefix: com.record
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  Record:
    type: application
    platform: iOS
    sources:
      - Record
    settings:
      base:
        INFOPLIST_FILE: Record/Info.plist
        CODE_SIGN_ENTITLEMENTS: Record/Record.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: sangmin.record.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: complete
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
